version: "3"
services:
  expo_app:
    container_name: expo_app
    build:
      context: .
      dockerfile: docker/reactnative/Dockerfile
    tty: true
    volumes:
      - ./src:/app/src
    environment:
      - REACT_NATIVE_PACKAGER_HOSTNAME=${LOCAL_IP_ADDR}
    ports:
      - 19000:19000
      - 19001:19001
      - 19002:19002
      - 19006:19006